version: '3.8'
services:
  app:
    build: .
    container_name: job_data_analysis
    volumes:
      - .:/app
    ports:
      - "8888:8888"
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://user:password@db:5432/job_data
    depends_on:
      - db
    command: ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--allow-root", "--NotebookApp.token=''"]

  db:
    image: postgres:13
    container_name: job_data_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: job_data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
